### PR TITLE
Fix maximum number of gravatars shown

### LINKED ISSUE #11: A maximum of 20 gravatars shown despite admin setting
Only 20 gravatars are ever shown despite changing the `Maximum Gravatars To Show` setting to something higher, or leaving it blank for all. 

This is due to `'posts_per_page' => 20` in EDD's `get_connected_logs()`, method.

Temp fix listed here:
https://wordpress.org/support/topic/not-enough-gravatars-showing-despite-setting/#post-10017733

### PR DESCRIPTION
**Pull request by robincornett**
Fixes #11

### CODE REVIEW

**Review by LisaCee — APPROVED** [review]
It took a little work to figure out how to test this, but it works for me.

Here's what I did:
- I changed the posts per page (Settings > Reading) to something smaller than the amount of purchases (Gravatars)
- I set the maximum amount of Gravatars to show to be greater than the posts per page

In 1.0.5, it only showed me Gravatars < posts per page. This branch displays Gravatars < maximum Gravatars.

File: edd-purchase-gravatars.php [hunk 1]
```diff
@@ -276,13 +271,14 @@ public function gravatars( $download_id = false, $title = '' ) {
...
+			$i       = 0;
+			$maximum = edd_get_option( 'edd_pg_maximum_number' );
 
 			if ( $payment_ids ) {
 				foreach ( $payment_ids as $id ) {
 
 					// EDD saves a blank option even when the control is turned off, hence the extra check
-					if ( isset( $edd_options['edd_pg_maximum_number'] ) && '' != $edd_options['edd_pg_maximum_number'] && $i == $edd_options['edd_pg_maximum_number'] ) {
+					if ( ! empty( $maximum ) && $i >= (int) $maximum ) {
 						continue;
```
Comment (ashleyfae) [inline edd-purchase-gravatars.php:282]:
```suggestion
						break;
```

I know it's not part of your PR, but `continue` will just make it keep going, and keep skipping, all until it's done. Whereas `break` will actually end the `foreach` loop completely, which is more in line with what we want.

**Review by ashleyfae — APPROVED** [review]
